### ISSUE TITLE
不能搜索空间下面的内容

### ISSUE THREAD

**Issue by huujiee** [yezige/yuque-search#1]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/6769510/198484880-182080ae-9faf-440b-b2d8-f8848629a557.png">

如图
只能搜索个人空间的文章，不能搜索出被贡献的空间的文章，是正常的吗？

**Comment by yezige** [comment]
经测试确实是无法搜索的，你的Token只是你个人环境的，个人和团队的空间是隔离的，目前看是的

**Comment by yezige** [comment]
> <img alt="image" width="574" src="https://user-images.githubusercontent.com/6769510/198484880-182080ae-9faf-440b-b2d8-f8848629a557.png">
> 
> 如图 只能搜索个人空间的文章，不能搜索出被贡献的空间的文章，是正常的吗？

经测试，找到了新的方法，是可以搜索的，考虑过几天更新一版，感谢支持

**Comment by huujiee** [comment]
> > <img alt="image" width="574" src="https://user-images.githubusercontent.com/6769510/198484880-182080ae-9faf-440b-b2d8-f8848629a557.png">
> > 如图 只能搜索个人空间的文章，不能搜索出被贡献的空间的文章，是正常的吗？
> 
> 经测试，找到了新的方法，是可以搜索的，考虑过几天更新一版，感谢支持

👍🏻

**Comment by yezige** [comment]
目前插件功能已开发完成，但发现语雀接口有个严重的bug，正在沟通解决，会延迟几天发布

**Comment by yezige** [comment]
@huujiee 您好，抱歉发布进度拖了这么久，由于语雀接口有一些仍未解决的小问题（如下图）
![image](https://user-images.githubusercontent.com/11436166/213343659-4bd09316-30d2-45ce-ab27-1d5de24bbeb7.png)

所以插件迟迟未发布，实际插件代码部分早先已经开发完成，迫于实在等的心急，我先尝试发布到Chrome Store，您先试用，有问题反馈我吧，插件最新版本：v1.0.5.2
