### ISSUE TITLE
可不可以支持Edge

### ISSUE THREAD

**Issue by jjtenger** [yezige/yuque-search#2]
如题，不想再下一个chrome了，可不可以支持一下Edge浏览器

**Comment by yezige** [comment]
我试一下edge store，这几天过来反馈

**Comment by jjtenger** [comment]
好的，谢谢

**Comment by yezige** [comment]
已提交，正在等待审核，感谢支持
![image](https://user-images.githubusercontent.com/11436166/212220354-3567a444-5dee-48bc-9ae6-6f11e513f76b.png)

**Comment by yezige** [comment]
@jjtenger 已成功上架Edge Store，链接：https://microsoftedge.microsoft.com/addons/detail/madffokkiogcnjokeoibaadkjmjpbhhe

**Comment by jjtenger** [comment]
> @jjtenger 已成功上架 Edge (边缘) Store，链接：[https://microsoftedge.microsoft.com/addons/ detail (细节) /madffokkiogcnjokeoibaadkjmjpbhhe](https://microsoftedge.microsoft.com/addons/detail/madffokkiogcnjokeoibaadkjmjpbhhe)

好勒，谢谢了
