### ISSUE TITLE
🔍搜索内容不完整

### ISSUE THREAD

**Issue by Yokileforever** [yezige/yuque-search#3]
1. 我的book中有很多篇文章有 材料 这个词语，但实际搜索却只能搜索到一篇文章。

**Comment by yezige** [comment]
您好，你多换几个更精确的词搜索试试呢，语雀的搜索接口有很多问题，例如无空格会当成一整个词搜、code中的文字不会被搜到、很多文章没有被搜到等等问题。

**Comment by Yokileforever** [comment]
好的。

**Comment by yezige** [comment]
常用的文章会被优先展示，且没有分页限制结果条数，所以目前通过更合适的关键词进行搜索是最优解。感谢使用
